const stringsByFile = {
  "./toast/toast-region.tsx": [
    "@react-aria/toast",
    "@react-aria/toast",
    "@react-stately/toast",
    "@react-stately/toast",
    "react",
    "react-aria-components",
    "react-dom",
    "tailwind-merge",
    "../button",
    "../icons",
    "./toast-queue",
    "bottom-right",
    "bottom-6 right-6 anim ",
    "bottom-left",
    "bottom-6 left-6",
    "bottom-center",
    "bottom-6 left-1/2 -translate-x-1/2",
    "top-left",
    "top-6 left-6 ",
    "top-center",
    "top-6 left-1/2 -translate-x-1/2",
    "top-right",
    "top-6 right-6",
    "toast-region fixed isolate z-20 flex flex-col gap-2 outline-none",
    "closeButtonProps",
    "children",
    "",
    "bottom-right",
    "bottom-right",
    "top-right",
    "entering",
    "duration-200 slide-in-from-right animate-in ease-out",
    "",
    "bottom-left",
    "top-left",
    "entering",
    "duration-200 slide-in-from-left animate-in ease-out",
    "",
    "bottom-center",
    "top-center",
    "entering",
    "duration-200 slide-in-from-top animate-in ease-out",
    "",
    "flex flex-1 rounded-lg bg-background outline-none",
    "toast flex w-[min(85vw,360px)] gap-1 rounded-lg border px-3 py-2 shadow-sm transition",
    "border-border/50 bg-background",
    "error",
    "border-destructive1 bg-destructive0",
    "warning",
    "border-warning1 bg-warning",
    "success",
    "border-success1 bg-success0",
    "flex flex-1 items-center gap-2 self-center",
    "error",
    "http://www.w3.org/2000/svg",
    "24",
    "24",
    "0 0 24 24",
    "none",
    "currentColor",
    "2",
    "round",
    "round",
    "mt-1 flex size-5 self-start text-destructive",
    "M12 16h.01",
    "M12 8v4",
    "M15.312 2a2 2 0 0 1 1.414.586l4.688 4.688A2 2 0 0 1 22 8.688v6.624a2 2 0 0 1-.586 1.414l-4.688 4.688a2 2 0 0 1-1.414.586H8.688a2 2 0 0 1-1.414-.586l-4.688-4.688A2 2 0 0 1 2 15.312V8.688a2 2 0 0 1 .586-1.414l4.688-4.688A2 2 0 0 1 8.688 2z",
    "warning",
    "http://www.w3.org/2000/svg",
    "24",
    "24",
    "0 0 24 24",
    "none",
    "currentColor",
    "2",
    "round",
    "round",
    "mt-1 flex size-5 self-start text-warning",
    "m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3",
    "M12 9v4",
    "M12 17h.01",
    "success",
    "http://www.w3.org/2000/svg",
    "24",
    "24",
    "0 0 24 24",
    "none",
    "currentColor",
    "2",
    "round",
    "round",
    "mt-1 flex size-5 self-start text-success",
    "12",
    "12",
    "10",
    "m9 12 2 2 4-4",
    "flex flex-1 flex-col gap-1 text-sm/6",
    "font-medium",
    "plain",
    "sm",
    "rounded",
    "hover:bg-transparent",
    "Close",
    "text-muted/75 group-hover:text-foreground",
  ],
  "./accessible-icon.tsx": [
    'react',
    'svg',
    'ara-hidden',
    'aria-label',
    'aria-hidden',
    'true',
    'aria-label',
    'data-ui',
    'icon',
    'false',
    'sr-only',
  ],
  "./breadcrumbs.tsx": [
    'react-aria-components',
    'tailwind-merge',
    './link',
    './utils',
    './icons',
    'flex gap-1',
    'className',
    'flex items-center gap-1',
    "underline underline-offset-2 disabled:opacity-100 [&:not(:hover)]:decoration-muted",
    "size-4 text-muted",
  ],
  "./clipboard.tsx": [
    "react",
    "@/hooks/use-clipboard",
    "./button",
    "./icons",
    "./tooltip",
    "Copy",
    "Copied to clipboard",
    "plain",
    "children",
  ],
  "./combobox.tsx": [
    'react',
    'react-aria-components',
    './button',
    './utils',
    'tailwind-merge',
    './select',
    './field',
    './icons',
    "comboBox",
    'w-full min-w-56',
    "control",
    'isolate',
    'grid',
    'grid-cols-[36px_1fr_minmax(40px,max-content)_minmax(40px,max-content)]',
    'sm:grid-cols-[36px_1fr_minmax(36px,max-content)_minmax(36px,max-content)]',
    'items-center',
    'sm:[&>[data-ui=icon]:has(+input)]:size-4',
    '[&>[data-ui=icon]:has(+input)]:size-5',
    '[&>[data-ui=icon]:has(+input)]:row-start-1',
    '[&>[data-ui=icon]:has(+input)]:col-start-1',
    '[&>[data-ui=icon]:has(+input)]:place-self-center',
    '[&>[data-ui=icon]:has(+input)]:text-muted',
    '[&>[data-ui=icon]:has(+input)]:z-10',
    '[&>input]:row-start-1',
    '[&>input]:col-span-full',
    '[&>input:not([class*=pe-])]:pe-10',
    'sm:[&>input:not([class*=pe-])]:pe-9',
    '[&>input:has(+[data-ui=clear]:not(:last-of-type))]:pe-20',
    'sm:[&>input:has(+[data-ui=clear]:not(:last-of-type))]:pe-16',
    '[&:has([data-ui=icon]+input)>input]:ps-10',
    'sm:[&:has([data-ui=icon]+input)>input]:ps-8',
    '[&>[data-ui=trigger]]:row-start-1',
    '[&>[data-ui=trigger]]:-col-end-1',
    '[&>[data-ui=trigger]]:place-self-center',
    '[&>[data-ui=clear]]:row-start-1',
    '[&>[data-ui=clear]]:-col-end-2',
    '[&>[data-ui=clear]]:justify-self-end',
    '[&>[data-ui=clear]:last-of-type]:-col-end-1',
    '[&>[data-ui=clear]:last-of-type]:place-self-center',
    "sm",
    "trigger",
    "plain",
    "text-muted group-hover:text-foreground sm:size-5",
    'onPress',
    '[&:not(:last-child)]:-me-1',
    'visible focus-visible:-outline-offset-2',
    'invisible',
    "clear",
    "sm",
    "plain",
    "Clear",
    "text-muted",
    "outline",
    "trigger",
    "sm",
    "me-1 flex font-normal peer-data-[focused=true]:hidden",
    "font-sans",
    "trigger",
    "me-1 hidden rounded-lg p-1 text-xs peer-data-[focused=true]:flex ltr:ms-1",
  ],
  "./date-field.tsx": [
    'react-aria-components',
    './utils',
    'tailwind-merge',
    '[&>:not(input)]:opacity-50',
    'children',
    "control",
    'group flex w-full items-center rounded-lg border bg-inherit shadow-sm',
    'invalid:border-destructive',
    '[&:has([data-disabled=true])]:opacity-50',
    'ring-offset-0',
    'block min-w-[150px]',
    'text-base/6 sm:text-sm/6',
    'px-2.5',
    'py-[calc(theme(spacing[2.5])-1px)] sm:py-[calc(theme(spacing[1.5])-1px)]',
    'inline rounded px-0.5 caret-transparent outline-0 type-literal:px-0',
    'data-[placeholder]:italic data-[placeholder]:text-muted',
    'focus:bg-accent focus:text-white focus:data-[placeholder]:text-white',
  ],
  "./dialog.tsx": [
    'react-aria-components',
    'tailwind-merge',
    'react',
    './heading',
    './button',
    './utils',
    './text',
    './icons',
    'react-aria-components',
    'alertdialog',
    'dialog',
    'relative flex max-h-[inherit] flex-col overflow-hidden outline-none',
    '--dialog-header-height',
    'string',
    'px-6 pb-2 pt-6',
    'relative flex w-full items-center px-6 pb-2 pt-6',
    'div',
    'flex max-h-[calc(var(--visual-viewport-height)-var(--visual-viewport-vertical-padding)-var(--dialog-header-height,0px)-var(--dialog-footer-height,0px))] flex-1 flex-col gap-2 overflow-auto px-6',
    'string',
    'div',
    '--dialog-footer-height',
    'mt-auto flex flex-col flex-col-reverse justify-end gap-3 p-6 sm:flex-row',
    'plain',
    'lg',
    'aria-label',
    'absolute end-3 top-3 p-1.5 text-muted/75 hover:text-foreground',
    'Close',
    "title",
  ],
  "./disclosure.tsx": [
    'react-aria-components',
    './utils',
    'react-aria-components',
    "trigger",
    'group flex items-center gap-x-1 rounded-md outline-none',
  ],
  "./empty-state.tsx": [
    'tailwind-merge',
    'react-aria-components',
    './text',
    './heading',
    'div',
    'flex h-full w-full flex-col items-center justify-center gap-1 p-4 text-center @container',
    'div',
    'mb-2 flex max-w-32 items-center justify-center @md:max-w-40',
    '[&>svg:not([class*=text-])]:text-muted [&>svg]:h-auto [&>svg]:min-w-12 [&>svg]:max-w-full',
    'text-balance',
    'max-w-prose text-balance',
    'div',
    'mt-3 flex flex-col items-center justify-center gap-4 p-2',
  ],
  "./field.tsx": [
    'react',
    'react-aria-components',
    'tailwind-merge',
    './utils',
    './text',
    'span',
    'aria-labelledby',
    '[&>[data-ui=label]:first-of-type:not([class*=mb])]:mb-2',
    "label",
    'inline-block min-w-max text-pretty',
    'group-disabled:opacity-50',
    "after:ms-0.5 after:text-destructive after:content-[',
    ']",
    'aria-describedby',
    'aria-describedby',
    "description",
    'aria-describedby',
    "description",
    'block group-disabled:opacity-50',
    "description",
    "description",
    'block text-pretty text-base/6 text-muted sm:text-sm/6',
    'group-disabled:opacity-50',
    "text-field",
    "errorMessage",
    'block text-base/6 text-destructive sm:text-sm/6',
    'w-full rounded-lg border bg-inherit shadow-sm outline-none',
    'px-2.5 py-[calc(theme(spacing[2.5])-1px)] sm:py-[calc(theme(spacing[1.5])-1px)]',
    'text-base/6 placeholder:text-muted sm:text-sm/6',
    'invalid:border-destructive',
    'disabled:opacity-50',
    'w-full rounded-lg border bg-inherit px-2.5 py-1 outline-none',
    'text-base/6 placeholder:text-muted sm:text-sm/6 ',
    'disabled:opacity-50',
    'invalid:border-destructive',
  ],
  "./file-trigger.tsx": [
    'react-aria-components',
  ],
  "./form.tsx": [
    'react-aria-components',
    'tailwind-merge',
    "max-w-4xl space-y-6",
  ],
  "./heading.tsx": [
    'react',
    'react-aria-components',
    'tailwind-merge',
    'react-aria',
    './utils',
    'div',
    'div',
    'outline-none',
    'outline-none',
    'div',
    'text-sm/6 text-muted',
  ],
  "./icons.tsx": [
    'tailwind-merge',
    './accessible-icon',
    'aria-label',
    'svg',
    "http://www.w3.org/2000/svg",
    "0 0 24 24",
    "currentColor",
    "M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z",
    "evenodd",
    "M1.323 11.447C2.811 6.976 7.028 3.75 12.001 3.75c4.97 0 9.185 3.223 10.675 7.69.12.362.12.752 0 1.113-1.487 4.471-5.705 7.697-10.677 7.697-4.97 0-9.186-3.223-10.675-7.69a1.762 1.762 0 0 1 0-1.113ZM17.25 12a5.25 5.25 0 1 1-10.5 0 5.25 5.25 0 0 1 10.5 0Z",
    "evenodd",
    'aria-label',
    'svg',
    "http://www.w3.org/2000/svg",
    "0 0 20 20",
    "currentColor",
    "evenodd",
    "M3.28 2.22a.75.75 0 0 0-1.06 1.06l14.5 14.5a.75.75 0 1 0 1.06-1.06l-1.745-1.745a10.029 10.029 0 0 0 3.3-4.38 1.651 1.651 0 0 0 0-1.185A10.004 10.004 0 0 0 9.999 3a9.956 9.956 0 0 0-4.744 1.194L3.28 2.22ZM7.752 6.69l1.092 1.092a2.5 2.5 0 0 1 3.374 3.373l1.091 1.092a4 4 0 0 0-5.557-5.557Z",
    "evenodd",
    "m10.748 13.93 2.523 2.523a9.987 9.987 0 0 1-3.27.547c-4.258 0-7.894-2.66-9.337-6.41a1.651 1.651 0 0 1 0-1.186A10.007 10.007 0 0 1 2.839 6.02L6.07 9.252a4 4 0 0 0 4.678 4.678Z",
    'aria-label',
    'svg',
    "http://www.w3.org/2000/svg",
    "0 0 20 20",
    "currentColor",
    "2",
    "evenodd",
    "M16.704 4.153a.75.75 0 0 1 .143 1.052l-8 10.5a.75.75 0 0 1-1.127.075l-4.5-4.5a.75.75 0 0 1 1.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 0 1 1.05-.143Z",
    "evenodd",
    'aria-label',
    'svg',
    "http://www.w3.org/2000/svg",
    "24",
    "24",
    "0 0 24 24",
    "none",
    "currentColor",
    "2",
    "round",
    "round",
    "M5 12h14",
    "M12 5v14",
    'aria-label',
    'svg',
    "http://www.w3.org/2000/svg",
    "24",
    "24",
    "0 0 24 24",
    "none",
    "currentColor",
    "2",
    "round",
    "round",
    "M5 12h14",
    'aria-label',
    'svg',
    "http://www.w3.org/2000/svg",
    "24",
    "24",
    "0 0 24 24",
    "none",
    "currentColor",
    "2",
    "round",
    "round",
    "M18 6 6 18",
    "m6 6 12 12",
    'aria-label',
    'svg',
    "http://www.w3.org/2000/svg",
    "1em",
    "1em",
    "0 0 56 56",
    "currentColor",
    "M11.992 49.574h32.016c4.899 0 7.36-2.437 7.36-7.265V13.69c0-4.828-2.461-7.265-7.36-7.265H11.992c-4.875 0-7.36 2.414-7.36 7.265v28.62c0 4.851 2.485 7.265 7.36 7.265m-.328-3.773c-2.086 0-3.258-1.102-3.258-3.282V20.419c0-2.156 1.172-3.281 3.258-3.281h32.649c2.085 0 3.28 1.125 3.28 3.281V42.52c0 2.18-1.195 3.28-3.28 3.28Zm11.742-20.25h1.383c.82 0 1.102-.235 1.102-1.055v-1.383c0-.82-.281-1.078-1.102-1.078h-1.383c-.82 0-1.078.258-1.078 1.078v1.383c0 .82.258 1.055 1.078 1.055m7.805 0h1.36c.843 0 1.101-.235 1.101-1.055v-1.383c0-.82-.258-1.078-1.102-1.078h-1.359c-.82 0-1.101.258-1.101 1.078v1.383c0 .82.28 1.055 1.101 1.055m7.781 0h1.383c.82 0 1.102-.235 1.102-1.055v-1.383c0-.82-.282-1.078-1.102-1.078h-1.383c-.82 0-1.101.258-1.101 1.078v1.383c0 .82.281 1.055 1.101 1.055m-23.367 7.664h1.383c.82 0 1.102-.235 1.102-1.055v-1.383c0-.82-.282-1.054-1.102-1.054h-1.383c-.82 0-1.101.234-1.101 1.054v1.383c0 .82.28 1.055 1.101 1.055m7.781 0h1.383c.82 0 1.102-.235 1.102-1.055v-1.383c0-.82-.281-1.054-1.102-1.054h-1.383c-.82 0-1.078.234-1.078 1.054v1.383c0 .82.258 1.055 1.078 1.055m7.805 0h1.36c.843 0 1.101-.235 1.101-1.055v-1.383c0-.82-.258-1.054-1.102-1.054h-1.359c-.82 0-1.101.234-1.101 1.054v1.383c0 .82.28 1.055 1.101 1.055m7.781 0h1.383c.82 0 1.102-.235 1.102-1.055v-1.383c0-.82-.282-1.054-1.102-1.054h-1.383c-.82 0-1.101.234-1.101 1.054v1.383c0 .82.281 1.055 1.101 1.055m-23.367 7.687h1.383c.82 0 1.102-.258 1.102-1.078v-1.383c0-.82-.282-1.054-1.102-1.054h-1.383c-.82 0-1.101.234-1.101 1.054v1.383c0 .82.28 1.078 1.101 1.078m7.781 0h1.383c.82 0 1.102-.258 1.102-1.078v-1.383c0-.82-.281-1.054-1.102-1.054h-1.383c-.82 0-1.078.234-1.078 1.054v1.383c0 .82.258 1.078 1.078 1.078m7.805 0h1.36c.843 0 1.101-.258 1.101-1.078v-1.383c0-.82-.258-1.054-1.102-1.054h-1.359c-.82 0-1.101.234-1.101 1.054v1.383c0 .82.28 1.078 1.101 1.078",
    'aria-label',
    'svg',
    "http://www.w3.org/2000/svg",
    "24",
    "24",
    "0 0 24 24",
    "none",
    "currentColor",
    "2",
    "round",
    "round",
    "m18 15-6-6-6 6",
    'aria-label',
    'svg',
    "http://www.w3.org/2000/svg",
    "24",
    "24",
    "0 0 24 24",
    "none",
    "currentColor",
    "2",
    "round",
    "round",
    "m6 9 6 6 6-6",
    'aria-label',
    'svg',
    "http://www.w3.org/2000/svg",
    "24",
    "24",
    "0 0 24 24",
    "none",
    "currentColor",
    "2",
    "round",
    "round",
    "m9 18 6-6-6-6",
    'aria-label',
    'svg',
    "http://www.w3.org/2000/svg",
    "24",
    "24",
    "0 0 24 24",
    "none",
    "currentColor",
    "2",
    "round",
    "round",
    "m15 18-6-6 6-6",
    'aria-label',
    'svg',
    "http://www.w3.org/2000/svg",
    "0 0 16 16",
    "currentColor",
    "evenodd",
    "M9.965 11.026a5 5 0 1 1 1.06-1.06l2.755 2.754a.75.75 0 1 1-1.06 1.06l-2.755-2.754ZM10.5 7a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Z",
    "evenodd",
    'aria-label',
    'svg',
    'animate-spin',
    "http://www.w3.org/2000/svg",
    "none",
    "0 0 24 24",
    "opacity-25",
    "12",
    "12",
    "10",
    "currentColor",
    "4",
    "opacity-75",
    "currentColor",
    "M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z",
    'aria-label',
    'svg',
    "http://www.w3.org/2000/svg",
    "24",
    "24",
    "0 0 24 24",
    "none",
    "currentColor",
    "2",
    "round",
    "round",
    "14",
    "14",
    "8",
    "8",
    "2",
    "2",
    "M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2",
  ],
  "./input-group.tsx": [
    'react-aria-components',
    'tailwind-merge',
    './utils',
    "control",
    'isolate',
    'flex',
    '[[data-ui=text-field]_&_]:grid',
    '[[data-ui=text-field]_&_]:grid-cols-[auto_1fr_auto]',
    '[[data-ui=text-field]_&>[data-ui=addon]:first-child]:col-start-1',
    '[[data-ui=text-field]_&>[data-ui=addon]:first-child]:row-start-1',
    '[[data-ui=text-field]_&>[data-ui=addon]:first-child]:z-10',
    '[[data-ui=text-field]_&>[data-ui=addon]:last-child]:-col-end-1',
    '[[data-ui=text-field]_&>[data-ui=addon]:last-child]:row-start-1',
    '[[data-ui=text-field]_&>[data-ui=addon]:first-child]:col-start-1',
    '[[data-ui=text-field]_&>[data-ui=addon]:first-child]:row-start-1',
    '[[data-ui=text-field]_&>[data-ui=addon]:first-child]:z-10',
    '[[data-ui=text-field]_&>[data-ui=addon]:last-child]:-col-end-1',
    '[[data-ui=text-field]_&>[data-ui=addon]:last-child]:row-start-1',
    '[[data-ui=text-field]_&>[data-ui=addon]]:border-0',
    '[[data-ui=text-field]_&>input]:col-span-full',
    '[[data-ui=text-field]_&>input]:row-start-1',
    '[[data-ui=text-field]_&>input:not(:first-child):not([class*=ps-])]:ps-10',
    'sm:[[data-ui=text-field]_&>input:not(:first-child):not([class*=ps-])]:ps-8',
    '[[data-ui=text-field]_&>input:not(:last-child):not([class*=pe-])]:pe-10',
    'sm:[[data-ui=text-field]_&>input:not(:last-child):not([class*=pe-])]:pe-8',
    ' ',
    '[[data-ui=text-field]_&>input:not(:first-child)]:rounded-s-none',
    '[[data-ui=text-field]_&>input:not(:last-child)]:rounded-e-none',
    '[[data-ui=text-field]_&>[data-ui=addon]:not(:first-child)]:border-s-0',
    '[[data-ui=text-field]_&>[data-ui=addon]:not(:last-child)]:border-e-0',
    ' ',
    '[&>[data-ui=native-select-field]>[data-ui=label]]:sr-only',
    '[&>[data-ui=native-select-field]_select]:min-w-max',
    '[&>[data-ui=native-select-field]_select]:ps-3.5',
    '[&>[data-ui=native-select-field]:not(:first-child)_select]:rounded-s-none',
    '[&>[data-ui=native-select-field]:not(:first-child)_select]:border-s-0',
    '[&>[data-ui=native-select-field]:not(:last-child)_select]:rounded-e-none',
    '[&>[data-ui=native-select-field]:not(:last-child)_select]:border-e-0',
    '[&>[data-ui=native-select-field]:last-child_select]:text-center',
    '[&>[data-ui=select]>[data-ui=label]]:sr-only',
    '[&>[data-ui=select]]:w-max',
    '[&>[data-ui=select]]:min-w-max',
    '[&>[data-ui=select]_button]:ps-3.5',
    '[&>[data-ui=select]:not(:first-child)_button]:rounded-s-none',
    '[&>[data-ui=select]:not(:first-child)_button]:border-s-0',
    '[&>[data-ui=select]:not(:has(+[aria-hidden]:last-child))_button]:border-e-0',
    '[&>[data-ui=select]:not(:has(+[aria-hidden]:last-child))_button]:rounded-e-none',
    '[&>[data-ui=select]:not(:first-child)_button]:text-end',
    '[&_button[data-variant=outline]]:border-border',
    '[&>button:not(:first-child)]:rounded-s-none',
    '[&>button:not(:first-child)]:border-s-0',
    '[&>button:not(:last-child)]:rounded-e-none',
    '[&>button:not(:last-child)]:border-e-0',
    '[&>[data-ui=text-field]>[data-ui=label]]:sr-only',
    '[&>[data-ui=text-field]]:flex-1',
    '[&>[data-ui=text-field]:not(:first-child)_input]:rounded-s-none',
    '[&>[data-ui=text-field]:not(:first-child)_input]:border-s-0',
    '[&>[data-ui=text-field]:not(:last-child)_input]:rounded-e-none',
    '[&>[data-ui=text-field]:not(:last-child)_input]:border-e-0',
    '[&>[data-ui=separator]]:bg-[linear-gradient(to_bottom,_theme(colors.border)_1px,_transparent_1px,_transparent_calc(100%_-_1px),_theme(colors.border)_calc(100%_-_1px))]',
    '[&_input]:shadow-none',
    '[&_button]:shadow-none',
    '[&_select]:shadow-none',
    '[&:has(>[data-ui=text-field])]:shadow-sm',
    '[&:has(>[data-ui=text-field])]:rounded-lg',
    ' ',
    '[&>[data-ui=separator]]:bg-border',
    ' ',
    '[&>[data-ui=separator]:has(+[data-ui=text-field]:focus-within)]:bg-none',
    '[&>[data-ui=separator]:has(+[data-ui=text-field]:focus-within)]:!bg-blue-500',
    '[&>[data-ui=separator]:has(+[data-ui=text-field][data-readonly]:focus-within)]:!bg-blue-300',
    '[&>[data-ui=separator]:has(+[data-ui=text-field][data-invalid]:not(:focus-within))]:bg-destructive',
    '[&>[data-ui=text-field]:focus-within+[data-ui=separator]]:bg-none',
    '[&>[data-ui=text-field]:focus-within+[data-ui=separator]]:!bg-blue-500',
    '[&>[data-ui=text-field][data-readonly]:focus-within+[data-ui=separator]]:!bg-blue-300',
    '[&>[data-ui=text-field][data-invalid]:not(:focus-within)+[data-ui=separator]]:bg-destructive',
    '[&>[data-ui=separator]:has(+[data-ui=native-select-field]:focus-within)]:bg-none',
    '[&>[data-ui=separator]:has(+[data-ui=native-select-field]:focus-within)]:bg-blue-500',
    '[&>[data-ui=native-select-field]:focus-within+[data-ui=separator]]:bg-none',
    '[&>[data-ui=native-select-field]:focus-within+[data-ui=separator]]:bg-blue-500',
    '[&>[data-ui=separator]:has(+[data-ui=select][data-focus-visible])]:bg-none',
    '[&>[data-ui=separator]:has(+[data-ui=select][data-focus-visible])]:!bg-blue-500',
    '[&>[data-ui=separator]:has(+[data-ui=select][data-invalid])]:bg-destructive',
    '[&>[data-ui=select][data-focus-visible]+[aria-hidden]+[data-ui=separator]]:bg-none',
    '[&>[data-ui=select][data-focus-visible]+[aria-hidden]+[data-ui=separator]]:!bg-blue-500',
    '[&>[data-ui=select][data-invalid]+[aria-hidden]+[data-ui=separator]]:bg-destructive',
    "addon",
    'grid',
    'text-base/6 sm:text-sm/6',
    'text-muted',
    'border-y',
    'place-content-center',
    'px-2.5',
    'first:border-s',
    'first:rounded-s-lg',
    'last:rounded-e-lg',
    'last:border-e',
    'group-focus-within:border-red-400',
    '[&>[data-ui=icon]]:size-5',
    'sm:[&>[data-ui=icon]]:size-4',
    '[&>[data-ui=icon]]:text-muted/65',
    'div',
    "separator",
    'w-[1px] shrink-0',
    ' ',
    "control",
    'shadow-sm',
    'grid',
    'grid-flow-col',
    'group',
    'items-center',
    'w-max',
    'rounded-lg border',
    'data-[invalid]:border-destructive',
    '[&>input]:border-0',
    '[&>input:focus]:border-0',
    '[&>input]:ring-0',
    '[&>input:focus]:ring-0',
    '[&>input]:shadow-none',
    '[&>input]:min-w-12',
    'sm:[&>input]:min-w-11',
    '[&>input:not(:first-of-type):not(:last-of-type)]:text-center',
    '[&>:not(input)]:text-muted',
  ],
  "./kbd.tsx": [
    'react-aria-components',
    'tailwind-merge',
    'div',
    'children',
    "kbd",
    'font-sans text-base/6 tracking-widest text-muted/75 sm:text-sm/6',
  ],
  "./link.tsx": [
    'react',
    'react-aria-components',
    './utils',
    'tailwind-merge',
    './slot',
    'relative inline-flex cursor-pointer items-center gap-1 rounded-lg outline-none hover:underline',
    'text-base/6 sm:text-sm/6',
    'disabled:no-underline disabled:opacity-50 disabled:cursor-default',
    '[&.border]:hover:no-underline',
    ' ',
  ],
  "./notification-badge.tsx": [
    'tailwind-merge',
    'span',
    'absolute right-1 top-1 flex size-2 rounded-full bg-red-600',
    'text-whit absolute right-0 top-0 flex h-4 -translate-y-1.5 translate-x-1 items-center justify-center rounded-full bg-red-600 text-[0.65rem] text-white',
    ' w-5',
    'w-4',
    ' ',
    "pb-0.5",
  ],
  "./number-field.tsx": [
    'react-aria-components',
    './field',
    './utils',
    './button',
    './separator',
    './icons',
    "control",
    "group isolate grid grid-cols-[auto_auto_1fr_auto_auto]",
    "decrement",
    "plain",
    "z-10 col-start-1 row-start-1 rounded-none hover:bg-transparent pressed:bg-transparent",
    "vertical",
    "col-start-2 row-start-1",
    'z-0',
    'col-span-full',
    'row-start-1',
    'px-[calc(theme(size.11)+10px)] sm:px-[calc(theme(size.9)+10px)]',
    "vertical",
    "-col-end-2 row-start-1",
    "increment",
    "-col-end-1 row-start-1 rounded-none hover:bg-transparent pressed:bg-transparent",
    "plain",
  ],
  "./password-input.tsx": [
    'react',
    'react-aria-components',
    './field',
    './button',
    './utils',
    './icons',
    "control",
    'grid',
    'grid-cols-[1fr_calc(theme(size.5)+20px)]',
    'sm:grid-cols-[1fr_calc(theme(size.4)+20px)]',
    ' ',
    'peer',
    'col-span-full',
    'row-start-1',
    'pe-10 sm:pe-9',
    'text',
    'password',
    "sm",
    "plain",
    "Show password",
    'group',
    'focus-visible:-outline-offset-1',
    'row-start-1',
    '-col-end-1',
    'place-self-center',
    ' ',
    "text-muted/75 group-hover:text-foreground",
    "text-muted/75 group-hover:text-foreground",
  ],
  "./pgagination.tsx": [
    'tailwind-merge',
    './button',
    './link',
    'react-aria-components',
    './icons',
    'aria-label',
    'Page navigation',
    'nav',
    "navigation",
    'mx-auto flex w-full justify-center gap-x-2',
    'div',
    'flex hidden gap-x-1 sm:flex',
    'Previous',
    "plain",
    'px-3.5 outline-offset-0 hover:no-underline',
    'Next',
    "plain",
    'px-3.5 outline-offset-1 hover:no-underline',
    'aria-label',
    'plain',
    'min-w-9 outline-offset-1 hover:no-underline',
    'span',
    'h-9 px-3.5',
  ],
  "./search-field.tsx": [
    'react-aria-components',
    './utils',
    './button',
    './field',
    './icons',
    "control",
    'isolate',
    'grid',
    'grid-cols-[calc(theme(size.5)+20px)_1fr_calc(theme(size.5)+20px)]',
    'sm:grid-cols-[calc(theme(size.4)+20px)_1fr_calc(theme(size.4)+20px)]',
    ' ',
    "col-start-1 row-start-1 size-5 place-self-center text-muted sm:size-4 z-10",
    '[&::-webkit-search-cancel-button]:hidden',
    'col-span-full',
    'row-start-1',
    'pe-10',
    'sm:pe-9',
    'ps-10',
    'sm:ps-8',
    "plain",
    "sm",
    "group-empty-invisible -col-end-1 row-start-1 place-self-center group-empty:invisible",
    "Clear",
  ],
  "./separator.tsx": [
    'react-aria',
    'tailwind-merge',
    'react-aria-components',
    'div',
    'horizontal',
    'text-sm/6',
    '[&>svg:not([class*=size])]:size-5',
    'before:border-border/35 after:border-border/35',
    'before:border-border/75 after:border-border/75',
    'vertical',
    'mx-4 flex flex-col items-center',
    "before:content-[',
    ']",
    'before:border-l',
    'before:flex-1',
    "after:content-[',
    ']",
    'after:border-r',
    'after:flex-1',
    'string',
    'before:mb-4 after:mt-4',
    'self-stretch',
    'my-2 flex items-center',
    "before:content-[',
    ']",
    'before:border-t',
    'before:flex-1',
    "after:content-[',
    ']",
    'after:border-t',
    'after:flex-1',
    'string',
    'before:me-4 after:ms-4',
    'border-border/35',
    'border-border/75',
    'vertical',
    'h-auto self-stretch border-l',
    'string',
    'mx-1',
    'h-px w-full self-stretch border-b',
    'string',
    'my-1',
  ],
  "./slot.tsx": [
    'react',
    "tailwind-merge",
    'asChild',
  ],
  "./status.tsx": [
    'tailwind-merge',
    'svg',
    'text-emerald-600',
    "http://www.w3.org/2000/svg",
    "0 0 512 512",
    "currentColor",
    "M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512z",
    'svg',
    'text-red-600',
    "currentColor",
    "http://www.w3.org/2000/svg",
    "0 0 512 512",
    "M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM175 175c9.4-9.4 24.6-9.4 33.9 0l47 47 47-47c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9l-47 47 47 47c9.4 9.4 9.4 24.6 0 33.9s-24.6 9.4-33.9 0l-47-47-47 47c-9.4 9.4-24.6 9.4-33.9 0s-9.4-24.6 0-33.9l47-47-47-47c-9.4-9.4-9.4-24.6 0-33.9z",
    'svg',
    'text-slate-400',
    "http://www.w3.org/2000/svg",
    "0 0 512 512",
    "none",
    "currentColor",
    "90",
    "round",
    "round",
    "256",
    "256",
    "213",
    'svg',
    "currentColor",
    'text-red-600',
    "true",
    "0 0 10 10",
    "http://www.w3.org/2000/svg",
    "M5 10A5 5 0 1 0 5 0a5 5 0 0 0 0 10ZM3.5 4.5h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1 0-1Z",
    "currentColor",
  ],
  "./tag-input.tsx": [
    "react",
    "react-aria-components",
    "react-stately",
    "tailwind-merge",
    "./field",
    "./tag-group",
    "<TagInputContext.Provider> is required",
    "tagGroupId",
    ",",
    "",
    " ",
    "",
    "",
    "",
    "Enter",
    ",",
    ";",
    "Backspace",
    "",
    "w-full",
    "control",
    "flex min-h-9 items-center rounded-md shadow-sm",
    "border has-[input[data-focused=true]]:border-blue-500",
    "has-[input[data-invalid=true][data-focused=true]]:border-blue-500 has-[input[data-invalid=true]]:border-destructive",
    "has-[input[data-focused=true]]:ring-1 has-[input[data-focused=true]]:ring-blue-500",
    "inline-flex flex-1 flex-wrap items-center gap-1 px-1.5 py-[5px]",
    "contents",
    "flex flex-1",
    "border-0 px-0.5 py-0 shadow-none focus:ring-0",
  ],
  "./text.tsx": [
    "react",
    "react-aria-components",
    "tailwind-merge",
    "./link",
    "./utils",
    "p",
    "text-pretty text-base/6 text-muted sm:text-sm/6",
    "strong",
    "strong",
    "font-medium text-foreground",
    "small",
    "small",
    "text-sm sm:text-xs",
    "underline underline-offset-4",
  ],
  "./time-field.tsx": [
    "react-aria-components",
    "tailwind-merge",
    "./utils",
    "items-start",
    "[&>:not(input)]:opacity-50",
  ],
  "./avatar.tsx": [
    "react",
    "tailwind-merge",
    "@/hooks/use-image-loading-status",
    "./accessible-icon",
    "./get-initials",
    "div",
    "currentColor",
    "0 0 24 24",
    "font-medium text-white",
    "50%",
    "50%",
    "middle",
    "middle",
    "middle",
    ".125em",
    "65%",
    "",
    " ",
    "img",
    "group relative flex size-10 shrink-0 items-center justify-center rounded-lg @container",
    "outline outline-1 -outline-offset-1 outline-black/5 dark:outline-white/20 ring-background",
    "[&.rounded-full>svg]:rounded-full [&>svg]:size-full [&>svg]:rounded-lg",
    "[&.rounded-full>img]:rounded-full [&>img]:size-full [&>img]:rounded-lg",
    "loaded",
    "object-cover",
    "aria-label",
    "aria-label",
    "<AvatarContext.Provider> is required",
    "@[32px]:w-2/5 @[40px]:w-1/3 @[64px]:w-1/4 @[128px]:w-1/5",
    "z-1 absolute bottom-0 end-0 z-10 rounded-full border-2 border-background bg-background",
    "translate-x-[15%] translate-y-[20%]",
    "[.rounded-full_&]:translate-x-[35%] [.rounded-full_&]:translate-y-[5%] rtl:[.rounded-full_&]:translate-y-[45%]",
    "@[40px]:[.rounded-full_&]:translate-x-[15%]",
    "@[64px]:[.rounded-full_&]:-translate-x-[5%] @[64px]:[.rounded-full_&]:-translate-y-[10%]",
    "@[128px]:[.rounded-full_&]:translate-x-[-20%]",
    "div",
    "flex items-center -space-x-2 rtl:space-x-reverse",
    "[&>[role=img]:not([class*=ring-4])]:ring-2",
    "flex-row-reverse ps-2 [&>[role=img]:first-of-type]:-ms-2",
  ],
  "./button.tsx": [
    "react",
    "react-aria-components",
    "tailwind-merge",
    "./icons",
    "./slot",
    "./utils",
    "accent",
    "success",
    "destructive",
    "sm",
    "lg",
    "solid",
    "outline",
    "plain",
    "unstyle",
    "group relative inline-flex gap-x-2 justify-center items-center",
    "font-semibold text-base/6 sm:text-sm/6 whitespace-nowrap outline-none rounded-lg",
    "border border-[var(--btn-bg)] dark:border-none dark:[--border-with:0px]",
    "bg-[var(--btn-bg)] hover:bg-[var(--btn-bg-hover)] pressed:bg-[var(--btn-bg-hover)]",
    "shadow-[inset_0_1px_0_0_rgba(255,255,255,0.1)]",
    "text-white",
    "border border-zinc-950/10 dark:border-white/15 border-b-zinc-950/15 dark:border-b-white/20",
    "hover:bg-zinc-50 pressed:bg-zinc-50 dark:hover:bg-zinc-800 dark:pressed:bg-zinc-800",
    "shadow-sm",
    "text-[var(--btn-color)]",
    "[--border-with:0px]",
    "hover:bg-zinc-100 dark:hover:bg-zinc-800",
    "text-[var(--btn-color)]",
    "h-8 sm:h-7 px-2 text-sm/6 sm:text-xs/6 rounded-md",
    "[&_svg:not([class*=size-])]:size-3",
    "size-8 sm:size-7 rounded-md",
    "[&_svg:not([class*=size-])]:size-5",
    "sm:[&_svg:not([class*=size-])]:size-4",
    "px-3 py-[calc(theme(spacing[2.5])-var(--border-with,1px))]",
    "sm:py-[calc(theme(spacing[1.5])-var(--border-with,1px))]",
    "[&_svg:not([class*=size-])]:size-5",
    "sm:[&_svg:not([class*=size-])]:size-4",
    "p-[calc(theme(spacing[2.5])-var(--border-with,1px))]",
    "sm:p-[calc(theme(spacing[1.5])-var(--border-with,1px))]",
    "[&_svg:not([class*=size-])]:size-5",
    "[&_svg]:m-0.5",
    "sm:[&_svg:not([class*=size-])]:size-4",
    "sm:[&_svg]:m-1",
    "px-4 py-[calc(theme(spacing[2.5])-var(--border-with,1px))]",
    "[&_svg:not([class*=size-])]:size-5",
    "p-[calc(theme(spacing[2.5])-var(--border-with,1px))]",
    "[&_svg:not([class*=size-])]:size-5",
    "[&_svg]:m-0.5",
    "solid",
    "unstyle",
    "relative outline-none rounded-lg",
    "md",
    "iconOnly",
    "button",
    "[--btn-bg:theme(colors.accent)]",
    "[--btn-bg-hover:theme(colors.accent/90%)]",
    "[--btn-bg:theme(colors.destructive)]",
    "[--btn-bg-hover:theme(colors.destructive/90%)]",
    "[--btn-bg:theme(colors.success)]",
    "[--btn-bg-hover:theme(colors.success/90%)]",
    "[--btn-color:theme(colors.foreground)]",
    "[--btn-color:theme(colors.accent)]",
    "[--btn-color:theme(colors.destructive)]",
    "[--btn-color:theme(colors.success)]",
    "solid",
    "accent",
    "foreground",
    "solid",
    "disabled:opacity-50",
    "data-[pending]:opacity-75",
    "data-[pending]:text-transparent",
    "absolute",
    "text-foreground",
    "group-data-[variant=solid]:text-zinc-300",
    "group-data-[pending]:sr-only",
    "group-data-[pending]:flex",
    "contents",
    "aria-hidden",
    "function",
    "absolute left-1/2 top-1/2 size-[max(100%,2.75rem)] -translate-x-1/2 -translate-y-1/2 [@media(pointer:fine)]:hidden",
    "true",
    "Button",
    "horizontal",
    "div",
    "horizontal",
    "vertical",
    "button-group",
    "group flex w-max items-center",
    "horizontal",
    "[&>button:first-of-type]:rounded-e-none",
    "[&>button:last-of-type]:rounded-s-none",
    "[&>button:not(:last-of-type)]:border-e-0",
    "shadow-sm [&>button:not(:first-of-type)]:border-s-0 [&>button]:shadow-none",
    "flex-col",
    "[&>button:first-of-type]:rounded-b-none",
    "[&>button:last-of-type]:rounded-t-none",
    "[&>button:not(:last-of-type)]:border-b-0",
    "shadow-sm [&>button:not(:first-of-type)]:border-t-0 [&>button]:shadow-none",
    "[&>button:not(:first-of-type):not(:last-of-type)]:rounded-none",
    "dark:[&>button[data-variant=solid]]:border-solid",
    "dark:[&>button[data-variant=solid]]:[--border-with:1px]",
    "[&>button[data-variant=solid]:not(:first-of-type)]:border-s-black/15",
  ],
  "./calendar.tsx": [
    'react-aria-components',
    './button',
    './utils',
    'tailwind-merge',
    './icons',
    'visibleDuration',
    "short",
    'flex size-9 cursor-default items-center justify-center rounded-lg text-sm outline-none',
    'hover:bg-zinc-100 dark:hover:bg-zinc-700',
    'pressed:bg-accent/90 pressed:text-white',
    'disabled:opacity-50',
    'selected:border selected:border-accent selected:dark:border-0',
    'selected:bg-accent selected:shadow-[inset_0_1px_0_0_rgba(255,255,255,0.1)]',
    'selected:text-white',
    'selected:invalid:border-destructive selected:invalid:bg-destructive selected:invalid:text-white',
    'unavailable:text-destructive unavailable:line-through unavailable:decoration-destructive',
    "errorMessage",
    "text-sm text-destructive",
    "flex w-full items-center gap-1",
    "previous",
    "plain",
    "Previous",
    "focus-visible:-outline-offset-2",
    'rtl',
    "text-muted sm:size-5",
    "text-muted sm:size-5",
    "mx-2 flex-1 text-center text-sm/6",
    "next",
    "plain",
    "Next",
    "focus-visible:-outline-offset-2",
    'rtl',
    "text-muted sm:size-5",
    "text-muted sm:size-5",
    "size-9 text-sm/6 font-normal text-muted",
  ],
  "./checkbox.tsx": [
    'react',
    'react-aria-components',
    './utils',
    'tailwind-merge',
    './field',
    './icons',
    'children',
    'vertical',
    'horizontal',
    'vertical',
    'div',
    "box",
    'flex flex-col group-data-[orientation=horizontal]:flex-row group-data-[orientation=horizontal]:flex-wrap',
    '[&_label]:has-[[data-ui=description]]:font-medium',
    'div',
    "field",
    'group flex flex-col gap-y-1',
    '[&_[data-ui=description]:not([class*=pe-])]:has-[label[data-position=left]]:pe-7',
    '[&_[data-ui=description]:not([class*=ps-])]:has-[label[data-position=right]]:ps-7',
    '[&_label]:has-[[data-ui=description]]:font-medium',
    '[&_[data-ui=description]]:has-[label[data-disabled]]:opacity-50',
    'left',
    'right',
    'right',
    'aria-describedby',
    'group flex items-center gap-x-3',
    'group-data-[orientation=horizontal]:text-nowrap',
    'data-[position=left]:flex-row-reverse',
    'data-[position=left]:justify-between',
    'text-base/6 sm:text-sm/6',
    'disabled:opacity-50',
    'flex flex-shrink-0 items-center justify-center',
    'size-[1.125rem] rounded shadow-sm sm:size-4',
    'border border-zinc-400/75 dark:border-[1.5px] dark:border-zinc-600',
    'group-invalid:border-destructive',
    'group-invalid:dark:border-destructive',
    'group-selected:border',
    'group-selected:border-accent',
    'group-selected:bg-accent',
    'group-selected:dark:border-0',
    'group-selected:dark:border-accent',
    'group-selected:shadow-[inset_0_1px_0_0_rgba(255,255,255,0.1)]',
    'group-indeterminate:border',
    'group-indeterminate:border-accent',
    'group-indeterminate:bg-accent',
    'group-indeterminate:dark:border-0',
    'group-indeterminate:dark:border-accent',
    'group-indeterminate:shadow-[inset_0_1px_0_0_rgba(255,255,255,0.1)]',
    "size-4 text-white sm:size-3.5",
    "size-4 text-white sm:size-3.5",
    'function',
  ],
  "./date-picker.tsx": [
    'react',
    'react-aria-components',
    './button',
    './calendar',
    './date-field',
    './dialog',
    './popover',
    './utils',
    'tailwind-merge',
    './icons',
    "control",
    'grid w-auto min-w-52',
    'grid-cols-[1fr_calc(theme(size.5)+20px)]',
    'sm:grid-cols-[1fr_calc(theme(size.4)+20px)]',
    ' ',
    'col-span-full',
    'row-start-1',
    'sm:pe-9',
    'pe-10',
    "plain",
    "sm",
    "trigger",
    'focus-visible:-outline-offset-1',
    'row-start-1',
    '-col-end-1',
    'place-self-center',
    ' ',
    'max-w-none rounded-xl',
    'dark:bg-zinc-800',
    'dark:ring-zinc-700',
    ' ',
    "bottom",
    "overflow-auto p-3",
    "control",
    'text w-auto min-w-52 flex-1 justify-between px-2.5 font-normal',
    "outline",
    '',
    "text-muted",
    "text-sm",
    "hidden",
    'max-w-none rounded-xl',
    'dark:bg-zinc-800',
    'dark:ring-zinc-700',
    ' ',
    "bottom",
    "overflow-auto p-3",
  ],
  "./date-range-picker.tsx": [
    'react',
    'react-aria-components',
    './button',
    './date-field',
    './dialog',
    './popover',
    './range-calendar',
    './utils',
    'tailwind-merge',
    './icons',
    "control",
    '[&:has([aria-valuetext=Empty]:) w-full',
    'grid grid-cols-[1fr_16px_1fr_40px] items-center sm:grid-cols-[1fr_16px_1fr_36px]',
    'group relative rounded-lg border bg-inherit shadow-sm',
    'group-invalid:border-destructive',
    '[&:has(_input[data-disabled=true])]:border-border/50',
    'min-w-60',
    'min-w-[278px]',
    "start",
    "flex min-w-fit border-none shadow-none focus-within:ring-0",
    "true",
    "place-self-center text-muted group-disabled:opacity-50",
    "end",
    "flex min-w-fit flex-1 border-none opacity-100 shadow-none focus-within:ring-0",
    "plain",
    "sm",
    "place-self-center focus-visible:-outline-offset-1",
    'max-w-none rounded-xl',
    'dark:bg-zinc-800',
    'dark:ring-zinc-700',
    ' ',
    "bottom",
    "overflow-auto p-3",
    "control",
    "outline",
    'w-full min-w-64 px-0 font-normal',
    'grid w-full items-center',
    'grid grid-cols-[1fr_16px_1fr_36px]',
    'grid-cols-[1fr_36px]',
    "min-w-fit px-2.5 text-base/6 sm:text-sm/6",
    "true",
    "place-self-center text-muted group-disabled:opacity-50",
    "min-w-fit px-2.5 text-base/6 sm:text-sm/6",
    "justify-self-start px-2.5 text-muted",
    "place-self-center",
    "start",
    "hidden",
    "end",
    "hidden",
    'max-w-none rounded-xl',
    'dark:bg-zinc-800',
    'dark:ring-zinc-700 ',
    ' ',
    "bottom",
    "overflow-auto p-3",
  ],
  "./dropzone.tsx": [
    'react-aria-components',
    './utils',
    'sm:min-w-96',
    'flex flex-shrink-0 flex-col items-center justify-center rounded-xl',
    'border border-dashed p-2',
    'drop-target:border-solid',
    'drop-target:bg-accent/20 drop-target:dark:bg-accent/75',
  ],
  "./grid-list.tsx": [
    'react-aria-components',
    './checkbox',
    './utils',
    'relative overflow-auto rounded-lg border p-1',
    'string',
    'relative -mb-px flex cursor-default select-none gap-3 rounded-md px-2 py-1.5 text-sm outline-none',
    'hover:bg-zinc100 dark:hover:bg-zinc-700',
    '[&:not(:last-child)]:mb-0.5',
    'selected:z-20',
    'disabled:opacity-50',
    'focus-visible:-outline-offset-2',
    "drag",
    'multiple',
    'toggle',
    "selection",
  ],
  "./hover-card.tsx": [
    'react',
    '@floating-ui/react',
    './heading',
    'tailwind-merge',
    'bottom',
    'end',
    'HoverCard components must be wrapped in <HoverCard />',
    'aria-label',
    'aria-labelledby',
    'max-w-72 rounded-lg bg-background dark:bg-zinc-800 p-1 shadow-lg outline-none ring-1 ring-zinc-950/10 dark:ring-white/15',
    'function',
  ],
  "./list-box.tsx": [
    'react',
    'react-aria-components',
    './utils',
    'tailwind-merge',
    './icons',
    'layout',
    'orientation',
    '[aria-selected=true]',
    'nearest',
    'smooth',
    'outline-none',
    'string',
    'group relative flex outline-0',
    'disabled:opacity-50',
    'string',
    'group flex cursor-default select-none items-center gap-x-1 rounded-md outline-none',
    'px-1.5 py-2.5 has-submenu:pe-0 sm:py-1.5',
    'text-base/6 sm:text-sm/6',
    'opacity-50',
    'bg-zinc-100 dark:bg-zinc-700',
    'text-destructive',
    'mt-1 size-4 self-start [[data-ui=select-value]_&]:hidden',
    'visible',
    'invisible',
    "item",
    '[&:first-child]:-mt-[1px]',
    '[&:not(:first-child)]:my-1.5',
    '[&:not(:first-child)]:border-t [&:not(:first-child)]:border-t-border/40',
    'sticky z-10 truncate bg-white px-7 pt-2 text-xs/4 text-muted dark:bg-zinc-800',
    'top-[0px] -mx-[1px] rounded-md backdrop-blur-md',
  ],
  "./menu.tsx": [
    'react-aria-components',
    'tailwind-merge',
    './popover',
    './button',
    './utils',
    './text',
    './icons',
    'react-aria-components',
    'outline',
    'gap-1',
    'pressed:scale-[0.97] pressed:opacity-75',
    'group-data-[ui=button-group]:pressed:scale-100',
    'group-data-[ui=button-group]:pressed:opacity-100',
    'unstyle',
    '',
    'px-2.5',
    'function',
    'ms-1',
    '[.justify-start_&]:ms-auto',
    '[[data-variant=outline]:not(:hover)_&]:text-muted',
    '[[data-variant=solid]:not(:hover)_&]:text-white/75',
    'dark:bg-zinc-800',
    'dark:ring-zinc-700',
    'max-w-72',
    'rounded-lg',
    'min-w-[max(144px,var(--trigger-width))]',
    'has-[[data-ui=item]_[data-ui=icon]]:min-w-[max(200px,var(--trigger-width))]',
    'has-[[data-ui=item]_kbd]:min-w-[max(176px,var(--trigger-width))]',
    'flex max-h-[inherit] flex-col overflow-auto outline-none',
    'p-1 has-[header]:px-2 has-[header]:pt-0',
    '[&_[data-ui=item]]:flex-1',
    '[&_[data-ui=item]]:grid',
    '[&_[data-ui=item]:has([data-ui=label])]:grid-cols-[16px_1fr_minmax(50px,max-content)]',
    '[&_[data-ui=item]]:items-center',
    '[&_[data-ui=item]]:gap-x-2',
    '[&_[data-ui=item]>[data-ui=icon]:not([class*=text-])]:text-muted',
    '[&_[data-ui=item][data-destructive]>[data-ui=icon]]:text-destructive/75',
    '[&:has([data-ui=icon]+[data-ui=label])_[data-ui=item]>[data-ui=icon]:not([class*=size-])]:size-4',
    '[&:has([data-ui=icon]+[data-ui=label])_[data-ui=item]>[data-ui=icon]]:col-start-1',
    '[&_[data-ui=item]>[data-ui=label]]:col-span-full',
    '[&:has([data-ui=icon]+[data-ui=label])_[data-ui=item]>[data-ui=label]]:col-start-2',
    '[&:has([data-ui=kbd])_[data-ui=item]>[data-ui=label]]:col-end-[-2]',
    '[&_[data-ui=item]>[data-ui=kbd]]:col-span-1',
    '[&_[data-ui=item]>[data-ui=kbd]]:row-start-1',
    '[&_[data-ui=item]>[data-ui=kbd]]:col-start-3',
    '[&_[data-ui=item]>[data-ui=kbd]]:justify-self-end',
    '[&_[data-ui=item][data-destructive]>[data-ui=kbd]]:text-destructive',
    '[&_[data-ui=item]>[data-ui=description]]:col-span-full',
    '[&:has([data-ui=kbd])_[data-ui=item]>[data-ui=description]]:col-end-[-2]',
    '[&:has([data-ui=icon]+[data-ui=label]+[data-ui=description])_[data-ui=item]>[data-ui=description]]:col-start-2',
    'aria-label',
    'my-1 w-[calc(100%-24px)] self-center border-t border-zinc-950/5 dark:border-white/10',
    'group flex cursor-default select-none items-center gap-x-2 outline-none',
    'px-3 py-2.5 sm:py-1.5 [&[data-selection-mode]]:px-2',
    'rounded-md',
    'text-base/6 sm:text-sm/6',
    'opacity-50',
    'bg-zinc-100 dark:bg-zinc-700',
    'text-destructive',
    'none',
    "icon",
    'flex w-4 self-start',
    'mt-[5px]',
    "size-4",
    "item",
    "-me-2 hidden size-4 text-muted group-data-[has-submenu]:inline-block",
    'span',
    "label",
    "label",
    'mb-0 truncate',
    'span',
    "description",
    "description",
    '[&:first-child]:-mt-[1px]',
    '[&:not(:first-child)]:my-1.5',
    '[&:not(:first-child)]:border-t [&:not(:first-child)]:border-t-border/40',
    '[&_header]:px-3',
    '[&:has([data-ui=item]>[data-ui=icon]+[data-ui=label])_header]:px-4',
    '[&:has([role=menuitemradio])_header]:ps-8',
    '[&:has([role=menuitemradio]>[data-ui=item]>[data-ui=icon]+[data-ui=label])_header]:ps-9',
    'sticky z-10 truncate bg-white pt-2 text-xs/4 text-muted dark:bg-zinc-800',
    'top-[0px] -mx-[1px] rounded-md backdrop-blur-md',
  ],
  "./meter.tsx": [
    'react-aria-components',
    './field',
    './utils',
    'flex flex-col gap-1',
    "flex justify-between gap-2",
    'text-destructive',
    "Alert",
    "inline-block size-5 align-text-bottom",
    "http://www.w3.org/2000/svg",
    "24",
    "24",
    "0 0 24 24",
    "none",
    "currentColor",
    "2",
    "round",
    "round",
    "m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3",
    "M12 9v4",
    "M12 17h.01",
    ' ',
    "relative h-2 w-64  rounded-full bg-gray-300 outline outline-1 -outline-offset-1 outline-transparent dark:bg-zinc-700",
    '%',
    'bg-success',
    'bg-blue-500',
    'bg-success',
    'bg-yellow-600',
    'bg-destructive',
  ],
  "./modal.tsx": [
    'react-aria-components',
    './utils',
    'sm:max-w-xs',
    'sm:max-w-sm',
    'sm:max-w-md',
    'sm:max-w-lg',
    'sm:max-w-xl',
    '2xl',
    'sm:max-w-2xl',
    '3xl',
    'sm:max-w-3xl',
    '4xl',
    'sm:max-w-4xl',
    '5xl',
    'sm:max-w-5xl',
    'h-full w-full',
    'left',
    'right',
    'className',
    'className',
    'className',
    'left',
    'fixed left-0 top-0 isolate z-20',
    'h-[--visual-viewport-height] w-full',
    'bg-zinc-950/40 dark:bg-zinc-950/50',
    'flex',
    'items-center',
    'text-center',
    'entering:animate-in',
    'entering:fade-in',
    'entering:duration-300',
    'entering:ease-out',
    'exiting:animate-out',
    'exiting:fade-out',
    'exiting:duration-200',
    'exiting:ease-in',
    'p-2 [--visual-viewport-vertical-padding:16px]',
    '[&:has([data-replacement=right])]:justify-end',
    'justify-center',
    'p-4',
    '[--visual-viewport-vertical-padding:32px]',
    '[&:has([role=dialog])]:items-end',
    '[&:has([role=dialog])]:pt-4',
    '[&:has([role=dialog])]:px-0',
    '[&:has([role=dialog])]:pb-0',
    '[&:has([role=dialog])]:[--visual-viewport-vertical-padding:16px]',
    'sm:[&:has([role=dialog])]:items-center',
    'sm:[&:has([role=dialog])]:p-4',
    'sm:[&:has([role=dialog])]:[--visual-viewport-vertical-padding:32px]',
    'max-h-full w-full overflow-hidden',
    'text-left align-middle',
    'shadow-lg',
    'bg-white dark:bg-zinc-900',
    'dark:ring-1 dark:ring-white/10',
    'sm:has-[[role=alertdialog]]:max-w-md sm:has-[[role=dialog]]:max-w-lg',
    'entering:animate-in',
    'entering:ease-out',
    'entering:duration-200',
    'exiting:animate-out',
    'exiting:ease-in',
    'exiting:duration-200',
    'h-full',
    'rounded-xl',
    'data-[replacement=left]:entering:slide-in-from-left',
    'data-[replacement=right]:entering:slide-in-from-right',
    'data-[replacement=left]:exiting:slide-out-to-left',
    'data-[replacement=right]:exiting:slide-out-to-right',
    'rounded-xl',
    'entering:zoom-in-95',
    'exiting:zoom-out-95',
    'has-[[role=dialog]]:rounded-t-xl ',
    'has-[[role=dialog]]:rounded-b-none',
    'sm:has-[[role=dialog]]:rounded-xl',
    'has-[[role=dialog]]:entering:zoom-in-100',
    'has-[[role=dialog]]:entering:slide-in-from-bottom',
    'sm:has-[[role=dialog]]:entering:zoom-in-95',
    'sm:has-[[role=dialog]]:entering:slide-in-from-bottom-0',
    'has-[[role=dialog]]:exiting:zoom-out-100',
    'has-[[role=dialog]]:exiting:slide-out-to-bottom',
    'sm:has-[[role=dialog]]:exiting:zoom-out-95',
    'sm:has-[[role=dialog]]:exiting:slide-out-to-bottom-0',
  ],
  "./multi-select.tsx": [
    'react',
    'react-aria-components',
    'react-stately',
    'react-aria',
    './field',
    './popover',
    './list-box',
    './button',
    'tailwind-merge',
    './tag-group',
    './utils',
    'children',
    'validate',
    'allowsEmptyCollection',
    'inputValue',
    'selectedKey',
    'inputValue',
    'className',
    'value',
    'onSelectionChange',
    'onInputChange',
    'base',
    '',
    '',
    '',
    '',
    '',
    '',
    'Backspace',
    '',
    "control",
    'relative',
    'pe-2',
    'flex min-h-9 w-[350px] flex-row flex-wrap items-center rounded-lg shadow-sm',
    'border has-[input[data-focused=true]]:border-blue-500',
    'has-[input[data-invalid=true][data-focused=true]]:border-blue-500 has-[input[data-invalid=true]]:border-destructive',
    'has-[input[data-focused=true]]:ring-1 has-[input[data-focused=true]]:ring-blue-500',
    "contents",
    'p-1',
    'outline-none',
    'group flex flex-1',
    "inline-flex flex-1 flex-wrap items-center gap-1 px-1.5",
    "flex-1 border-0 px-0.5 py-0 shadow-none outline-0 focus:ring-0",
    '',
    '',
    'aria-describedby',
    '',
    ' ',
    "sr-only",
    "plain",
    "http://www.w3.org/2000/svg",
    "24",
    "24",
    "0 0 24 24",
    "none",
    "currentColor",
    "2",
    "round",
    "round",
    "size-4",
    "m6 9 6 6 6-6",
    "max-w-none duration-0",
    "multiple",
    "flex max-h-[inherit] flex-col gap-1.5 overflow-auto p-1.5 outline-none has-[header]:pt-0 sm:gap-0",
    "plain",
    "top-50 absolute end-0 me-1 size-6 rounded p-0.5",
    "button",
    "http://www.w3.org/2000/svg",
    "24",
    "24",
    "0 0 24 24",
    "none",
    "currentColor",
    "2",
    "round",
    "round",
    "size-4 opacity-75",
    "m6 9 6 6 6-6",
    ',',
    'rounded-lg p-1.5 text-base/6 outline-0 focus-visible:outline-0 sm:text-sm/6',
    'bg-zinc-100 dark:bg-zinc-700',
  ],
  "./native-select.tsx": [
    'react',
    'react-aria',
    'tailwind-merge',
    './utils',
    './field',
    'react-aria-components',
    'div',
    'span',
    "native-select-field",
    'has-[select:disabled]:opacity-50',
    'select',
    "control",
    'relative flex transition',
    'aria-describedby',
    'w-full min-w-36',
    'appearance-none bg-transparent',
    'pe-8 ps-2.5',
    'py-[calc(theme(spacing[2.5])-1px)]',
    ' sm:py-[calc(theme(spacing[1.5])-1px)]',
    'rounded-lg border shadow-sm outline-none',
    'text-base/6 sm:text-sm/6',
    'hover:bg-zinc-100 dark:hover:bg-zinc-800',
  ],
  "./popover.tsx": [
    'react-aria-components',
    'react',
    './utils',
    'children',
    'SubmenuTrigger',
    'bg-white',
    'dark:bg-zinc-900',
    'shadow-md',
    'rounded-lg',
    'ring-1',
    'ring-zinc-950/10',
    'dark:ring-zinc-800',
    'entering:animate-in',
    'entering:ease-out',
    'entering:fade-in',
    'entering:placement-left:slide-in-from-right-1',
    'entering:placement-right:slide-in-from-left-1',
    'entering:placement-top:slide-in-from-bottom-1',
    'entering:placement-bottom:slide-in-from-top-1',
    'entering:duration-50',
    'exiting:animate-out',
    'exiting:ease-in',
    'exiting:fade-out',
    'exiting:placement-left:slide-out-to-right-1',
    'exiting:placement-right:slide-out-to-left-1',
    'exiting:placement-top:slide-out-to-bottom-1',
    'exiting:placement-bottom:slide-out-to-top-1',
    'exiting:duration-50',
  ],
  "./progress-bar.tsx": [
    'react-aria-components',
    './field',
    './utils',
    'flex flex-col gap-1',
    "flex justify-between gap-2",
    "text-sm text-muted",
    "relative h-2 w-64 overflow-hidden rounded-full bg-gray-300 outline outline-1 -outline-offset-1 outline-transparent dark:bg-zinc-700",
    'left-full duration-1000 ease-out animate-in slide-out-to-right-full repeat-infinite [--tw-enter-translate-x:calc(-16rem-100%)]',
    'left-0',
    '%',
  ],
  "./radio-group.tsx": [
    'react',
    'react-aria-components',
    './field',
    './utils',
    'tailwind-merge',
    'div',
    "box",
    'flex',
    'flex-col',
    'group-aria-[orientation=horizontal]:flex-row',
    'group-aria-[orientation=horizontal]:flex-wrap',
    '[&_label]:has-[[data-ui=description]]:font-medium',
    'div',
    "field",
    'group flex flex-col gap-y-1',
    '[&_label]:has-[[data-position=left]]:justify-between',
    '[&_[data-ui=description]:not([class*=pe-])]:has-[label[data-position=left]]:pe-7',
    '[&_[data-ui=description]:not([class*=ps-])]:has-[label[data-position=right]]:ps-7',
    '[&_[data-ui=description]]:has-[label[data-disabled]]:opacity-50',
    'left',
    'right',
    'children',
    'aria-describedby',
    'text-base/6 sm:text-sm/6',
    'disabled:opacity-50',
    'right',
    'aria-describedby',
    'group flex items-center gap-x-3',
    'group-aria-[orientation=horizontal]:text-nowrap',
    'data-[position=left]:flex-row-reverse',
    'data-[position=left]:justify-between',
    'text-base/6 sm:text-sm/6',
    'disabled:opacity-50',
    "radio",
    'grid size-[1.0625rem] shrink-0 place-content-center rounded-full shadow-sm',
    'border',
    'border-zinc-400/75',
    'dark:border-zinc-600',
    'group-invalid:border-destructive',
    'group-invalid:dark:border-destructive',
    'group-selected:dark:border-0',
    'group-selected:border-accent',
    'group-selected:bg-accent',
    'group-selected:shadow-[inset_0_1px_0_0_rgba(255,255,255,0.1)]',
    "rounded-full group-selected:size-1.5 group-selected:bg-white",
    'function',
  ],
  "./range-calendar.tsx": [
    'react-aria-components',
    './calendar',
    './utils',
    'tailwind-merge',
    'visibleDuration',
    "[&_td]:px-0",
    "short",
    "before:block before:w-full before:leading-[0.25rem] before:opacity-0 before:content-[',
    ']",
    'group size-9 cursor-default text-sm outline-none',
    'selected:bg-accent/[0.085] dark:selected:bg-accent/40',
    'invalid:selected:bg-destructive1 dark:invalid:selected:bg-destructive/30',
    'selection-start:rounded-s-lg',
    'selection-end:rounded-e-lg',
    '[td:first-child_&]:rounded-s-lg [td:last-child_&]:rounded-e-lg',
    ' ',
    'flex size-[calc(theme(size.9)-1px)] items-center justify-center',
    'group-hover:rounded-lg',
    'group-hover:bg-zinc-100',
    'dark:group-hover:bg-zinc-700',
    'group-pressed:bg-accent/90',
    'group-selected:group-hover:bg-accent/15',
    'group-selected:dark:group-hover:bg-accent/50',
    'group-selected:group-pressed:bg-accent',
    'group-selected:group-pressed:text-white',
    'group-disabled:opacity-50',
    'group-unavailable:text-destructive',
    'group-unavailable:decoration-destructive',
    'group-unavailable:line-through',
    'group-selected:group-selection-start:border',
    'group-selected:group-selection-start:dark:border-0',
    'group-selected:group-selection-start:border-accent',
    'group-selected:group-selection-start:rounded-lg',
    'group-selected:group-selection-start:bg-accent',
    'group-selected:group-selection-start:text-white',
    'group-selected:group-selection-start:shadow-[inset_0_1px_0_0_rgba(255,255,255,0.1)]',
    'group-selected:group-selection-start:group-hover:bg-accent/90',
    'group-selected:group-selection-start:dark:group-hover:bg-accent/90',
    'group-selected:group-selection-start:group-invalid:border-destructive',
    'group-selected:group-selection-start:group-invalid:bg-destructive',
    'group-selected:group-selection-start:group-invalid:text-white',
    'group-selected:group-selection-end:border',
    'group-selected:group-selection-end:dark:border-0',
    'group-selected:group-selection-end:border-accent',
    'group-selected:group-selection-end:rounded-lg',
    'group-selected:group-selection-end:bg-accent',
    'group-selected:group-selection-end:text-white',
    'group-selected:group-selection-end:shadow-[inset_0_1px_0_0_rgba(255,255,255,0.1)]',
    'group-selected:group-selection-end:group-hover:bg-accent/90',
    'group-selected:group-selection-end:dark:group-hover:bg-accent/90',
    'group-selected:group-selection-end:group-invalid:border-destructive',
    'group-selected:group-selection-end:group-invalid:bg-destructive',
    'group-selected:group-selection-end:group-invalid:text-white',
    'group-focus-visible:rounded-lg',
    "errorMessage",
    "text-sm text-destructive",
  ],
  "./select.tsx": [
    'react-aria-components',
    './list-box',
    './popover',
    './utils',
    'tailwind-merge',
    './text',
    './icons',
    "select",
    'w-full min-w-56',
    "control",
    'relative flex w-full cursor-default text-start items-center gap-x-1 rounded-lg border shadow-sm outline-none transition',
    'pe-8 ps-2.5',
    'py-[calc(theme(spacing[2.5])-1px)]',
    ' sm:py-[calc(theme(spacing[1.5])-1px)]',
    'group-invalid:border-destructive',
    'group:disabled:cursor-not-allowed group-disabled:opacity-50',
    'text-base/6 sm:text-sm/6',
    '[&>*:has(+[data-ui=select-value])>svg]:size-4',
    '[&>*:has(+[data-ui=select-value])>svg]:text-muted',
    'focus-visible:ring-offset-0',
    "flex items-center gap-x-2",
    "select-value",
    'flex-1 truncate  data-[placeholder]:text-muted dark:data-[placeholder]:text-white',
    '[&>[data-ui=item]]:flex',
    '[&>[data-ui=item]]:items-center',
    '[&>[data-ui=item]]:gap-x-2',
    '[&>[data-ui=item]_[data-ui=description]]:sr-only',
    '[&>[data-ui=item]_[data-ui=icon]:not([class*=size-])]:size-5',
    '[&>[data-ui=item]_[role=img]]:size-6',
    'sm:[&>[data-ui=item]_[data-ui=icon]:not([class*=size-])]:size-4',
    'sm:[&>[data-ui=item]_[role=img]]:size-5',
    'bottom',
    'w-[--trigger-width]',
    'dark:bg-zinc-800',
    'dark:ring-zinc-700',
    'flex max-h-[inherit] flex-col overflow-auto p-1 has-[header]:px-2 has-[header]:pt-0',
    '[&_[data-ui=item]]:grid',
    '[&_[data-ui=item]]:grid-cols-[minmax(16px,max-content)_1fr]',
    '[&_[data-ui=item]]:items-center',
    '[&_[data-ui=item]]:gap-x-2',
    '[&_[data-ui=item]>[data-ui=icon]:has(+[data-ui=label]):not([class*=size-])]:size-4',
    '[&_[data-ui=item]>[data-ui=label]]:col-span-full',
    '[&:has([data-ui=icon]+[data-ui=label])_[data-ui=item]>[data-ui=label]]:col-start-2',
    '[&:has([data-ui=icon]+[data-ui=label]+[data-ui=description])_[data-ui=item]>[data-ui=description]]:col-start-2',
    '[&_[data-ui=item]>[role=img]:has(+[data-ui=label])]:size-5',
    '[&:has([role=img]+[data-ui=label])_[data-ui=item]>[data-ui=label]]:col-start-2',
    '[&_[data-ui=item]>[role=img]:has(+[data-ui=label]+[data-ui=description])]:size-7',
    '[&_[data-ui=item]>[role=img]:has(+[data-ui=label]+[data-ui=description])]:self-start',
    '[&_[data-ui=item]>[role=img]:has(+[data-ui=label]+[data-ui=description])]:mt-0.5',
    '[&_[data-ui=item]>[role=img]:has(+[data-ui=label]+[data-ui=description])]:row-start-1',
    '[&_[data-ui=item]>[role=img]:has(+[data-ui=label]+[data-ui=description])]:row-end-3',
    '[&:has([role=img]+[data-ui=label]+[data-ui=description])_[data-ui=item]>[data-ui=label]]:leading-5',
    '[&:has([role=img]+[data-ui=label]+[data-ui=description])_[data-ui=item]>[data-ui=description]]:col-row-2',
    '[&:has([role=img]+[data-ui=label]+[data-ui=description])_[data-ui=item]>[data-ui=description]]:col-start-2',
    '[&:first-child]:-mt-[1px]',
    '[&:not(:first-child)]:my-1.5',
    '[&:not(:first-child)]:border-t [&:not(:first-child)]:border-t-border/40',
    'sticky z-10 truncate bg-white ps-8 pt-2 text-xs/4 text-muted dark:bg-zinc-800',
    'top-[0px] -mx-[1px] rounded-md',
    'string',
    'group flex cursor-default select-none items-center gap-x-2 rounded-md outline-none',
    'px-1.5 py-2.5 has-submenu:pe-0 sm:py-1.5',
    'text-base/6 sm:text-sm/6',
    'disabled:opacity-50',
    'focus:bg-zinc-100 focus:dark:bg-zinc-700',
    'text-destructive',
    'invisible mt-1 size-4 self-start group-selected:visible [[data-ui=select-value]_&]:hidden',
    "item",
    'w-full',
    'span',
    "label",
    "label",
    'mb-0 truncate w-full',
    'span',
    "description",
    "description",
  ],
  "./skeleton.tsx": [
    'tailwind-merge',
    'animate-pulse rounded-md bg-zinc-200 dark:bg-zinc-700',
  ],
  "./slider.tsx": [
    "react-aria-components",
    "tailwind-merge",
    "./utils",
    "react-aria-components",
    "flex flex-col gap-2 orientation-horizontal:min-w-64 orientation-vertical:items-center",
    "absolute top-[50%] translate-y-[-50%] rounded-full",
    "group-orientation-horizontal:h-1",
    "group-orientation-horizontal:w-full",
    "group-orientation-vertical:left-[50%]",
    "group-orientation-vertical:h-full",
    "group-orientation-vertical:w-[6px]",
    "group-orientation-vertical:translate-x-[-50%]",
    "group-orientation-vertical:translate-y-[-50%]",
    "group-disabled:opacity-50",
    "state",
    "orientation",
    "0",
    "horizontal",
    "auto",
    "translate(-50%,0px)",
    "group relative flex w-full items-center orientation-horizontal:h-7 orientation-vertical:h-44 orientation-vertical:w-7",
    "bg-zinc-200 dark:bg-zinc-300",
    "bg-accent",
    "",
    "size-5 rounded-full border bg-white shadow-xl dark:border-0",
    "group-orientation-horizontal:top-[50%] group-orientation-vertical:left-[50%]",
    "dragging:border-8  dragging:border-accent",
    "disabled:cursor-not-allowed",
  ],
  "./switch.tsx": [
    'react',
    'react-aria-components',
    './utils',
    'tailwind-merge',
    './field',
    'div',
    "box",
    'flex flex-col',
    '[&_label]:has-[[data-ui=description]]:font-medium',
    'div',
    "field",
    'group flex flex-col gap-y-1',
    '[&_[data-ui=description]:not([class*=pe-])]:has-[label[data-position=left]]:pe-[calc(theme(width.8)+16px)]',
    '[&_[data-ui=description]:not([class*=ps-])]:has-[label[data-position=right]]:ps-[calc(theme(width.8)+12px)]',
    '[&_label]:has-[[data-ui=description]]:font-medium',
    '[&_[data-ui=description]]:has-[label[data-disabled]]:opacity-50',
    'left',
    'right',
    'right',
    'aria-describedby',
    'group/control flex items-center gap-x-3',
    'data-[position=left]:flex-row-reverse',
    'data-[position=left]:justify-between',
    'text-base/6 sm:text-sm/6',
    'disabled:opacity-50',
    'h-5 w-8 cursor-default rounded-full px-0.5 shadow-inner',
    'transition duration-200 ease-in-out',
    'flex shrink-0 items-center',
    'bg-zinc-200',
    'dark:bg-transparent',
    'border',
    'group-selected/control:border-accent',
    'group-selected/control:dark:border-0',
    'group-selected/control:bg-accent',
    'group-selected/control:dark:bg-accent',
    'group-selected/control:shadow-[inset_0_0_0_1px_rgba(255,255,255,0.1)]',
    'group-disabled/control:bg-gray-200',
    'group-disabled/control:dark:bg-zinc-700',
    'h-[0.95rem] w-[0.95rem] rounded-full bg-white shadow-sm',
    'translate-x-0 transform transition duration-200 ease-in-out',
    'border',
    'group-selected/control:border-accent',
    'group-selected/control:translate-x-[78%]',
    'group-selected/control:rtl:-translate-x-[78%]',
    'function',
  ],
  "./table.tsx": [
    'react-aria-components',
    'tailwind-merge',
    './checkbox',
    './utils',
    './icons',
    "relative max-h-[280px] w-[550px] scroll-pt-[2.281rem] overflow-auto rounded-lg border",
    "border-separate border-spacing-0",
    'cursor-default border-b text-start text-sm font-semibold [&:focus-within]:z-20 [&:hover]:z-20',
    "flex items-center",
    "presentation",
    'outline-none',
    'flex h-5 flex-1 items-center gap-1 overflow-hidden px-2',
    "truncate",
    'descending',
    'rotate-180',
    '',
    "size-4 text-muted",
    'outline-none',
    'box-content h-5 w-[1.5px] translate-x-[8px] cursor-col-resize rounded bg-border bg-clip-content px-[8px] py-1 -outline-offset-2 resizing:w-[2px] resizing:bg-accent resizing:pl-[7px] forced-colors:bg-[ButtonBorder] forced-colors:resizing:bg-[Highlight]',
    'sticky top-0 z-10 rounded-t-lg  backdrop-blur-md',
    "after:content-[',
    ']",
    'after:flex-1',
    'toggle',
    "cursor-default border-b p-2 text-start text-sm font-semibold",
    'multiple',
    "selection",
    'focus-visible:outline-none',
    'focus-visible:rounded',
    'focus-visible:-outline-offset-2',
    'group/row relative cursor-default select-none text-sm  disabled:text-muted',
    'hover:bg-zinc-100 dark:hover:bg-zinc-700',
    'hover:selected:bg-zinc-100 dark:hover:selected:bg-zinc-700',
    'selected:bg-accent/5 dark:selected:bg-accent/35',
    "drag",
    'toggle',
    "selection",
    'outline-none',
    'focus-visible:rounded',
    'focus-visible:-outline-offset-2',
    'truncate border-b p-2 group-last/row:border-b-0',
  ],
  "./tabs.tsx": [
    "react",
    "react-aria-components",
    "./utils",
    "underline",
    "pills",
    "segment",
    "vertical",
    "horizontal",
    "underline",
    "horizontal",
    "underline",
    "pills",
    "segment",
    "underline",
    "horizontal",
    "manual",
    "group flex",
    "horizontal",
    "flex-col",
    "flex-row",
    "whitespace-nowrap",
    "flex-col",
    "w-full space-x-4 border-b",
    "space-y-3.5 self-start border-l",
    "space-x-4",
    "space-y-2",
    "gap-x-4",
    "rounded-lg",
    "bg-zinc-100",
    "p-1",
    "dark:bg-zinc-600/45",
    "dark:border",
    "dark:border-zinc-600/30",
    "flex overflow-x-auto pb-px pl-px",
    "flex",
    "text-base/6 sm:text-sm/6",
    "py-4",
    "px-4",
    "px-5 py-4",
    "pl-8",
    "px-3 py-4",
    "flex-1 outline-0",
    "before:absolute",
    "before:bg-accent",
    "before:bottom-[-1.5px]",
    "before:w-full",
    "before:inset-x-0",
    "selected:before:h-[2px]",
    "p-2",
    "before:inset-y-0",
    "before:selected:bg-accent",
    "before:selected:left-[-1.5px]",
    "before:selected:w-[2px]",
    "px-4",
    "flex",
    "items-center",
    "px-3",
    "py-2",
    "rounded-lg",
    "selected:bg-accent",
    "selected:text-white",
    "flex-1",
    "justify-center",
    "px-6",
    "py-1",
    "selected:bg-background",
    "dark:selected:bg-zinc-600",
    "selected:text-foreground",
    "selected:shadow-sm",
    "selected:rounded-[calc(theme(borderRadius.lg)-2px)]",
    "[&>[data-ui=icon]:not([class*=size-])]:size-4",
    "relative flex items-center gap-x-3 rounded font-medium outline-none outline-0",
    "disabled:opacity-50",
    "[&>[data-ui=icon]:not([class*=size-])]:size-[1.125rem]",
    "[&:not([data-selected])]:text-muted",
    "[&:not([data-selected])]:hover:text-foreground",
    "focus-visible:ring-2",
  ],
  "./tag-group.tsx": [
    "react",
    "react-aria-components",
    "tailwind-merge",
    "./icons",
    "./utils",
    "selected:border-accent",
    "selected:bg-accent",
    "selected:text-white",
    "selected:outline-0",
    "bg-success/10",
    "border-success1",
    "dark:bg-success/35",
    "dark:border-success/40",
    "selected:bg-success",
    "selected:border-success",
    "selected:dark:bg-success",
    "selected:text-white",
    "bg-warning/10",
    "border-warning1",
    "dark:bg-warning/35",
    "dark:border-warning/40",
    "selected:bg-warning",
    "selected:border-warning",
    "selected:dark:bg-warning",
    "selected:text-white",
    "bg-destructive/10",
    "border-destructive1",
    "dark:bg-destructive/35",
    "dark:border-destructive/40",
    "selected:bg-destructive",
    "selected:border-destructive",
    "selected:dark:bg-destructive",
    "selected:text-white",
    "default",
    "flex flex-col gap-1",
    "default",
    "flex flex-wrap gap-1",
    "string",
    "flex max-w-fit cursor-default items-center gap-1 rounded-md border px-1 py-0.5 text-xs transition",
    "focus-visible:outline-offset-1",
    "disabled:opacity-50",
    "remove",
    "",
    "flex cursor-default items-center justify-center rounded-full p-0.5 outline-0 transition-[background-color] hover:bg-black/10 pressed:bg-black/20 dark:hover:bg-white/10 dark:pressed:bg-white/20",
    "size-3",
  ],
  "./tooltip.tsx": [
    "react",
    "react-aria",
    "react-aria-components",
    "./utils",
    "react-aria-components",
    "children",
    "shadow-xs group max-w-56 text-pretty rounded-lg bg-zinc-950 dark:bg-zinc-800 p-2 text-xs text-white dark:shadow-none",
    "0 0 8 8",
    "fill-zinc-950 stroke-zinc-950 stroke-[0.5px] group-placement-left:-rotate-90 group-placement-right:rotate-90 group-placement-bottom:rotate-180",
    "M0 0 L4 4 L8 0",
    "div",
    "presentation",
  ],
};
